name: Python application

on: 
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
       docker build --tag python-app:v1 .
       docker images
    - name: Push image to dockerhub
      run: |
         docker push python-app:v1
       
